apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: collaboration-board
data:
  POSTGRES_DB: collaboration_board
  POSTGRES_USER: postgres
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:80,http://localhost"
